repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-yaml
        exclude: .github/conda/meta.yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-case-conflict
      - id: check-merge-conflict
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
  - repo: https://gitlab.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        types: [file, python]
  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.981
    hooks:
      - id: mypy
        # taken from https://github.com/pre-commit/mirrors-mypy/issues/33#issuecomment-735449356
        args: [src, --config-file=pyproject.toml]
        pass_filenames: false
        # Same list of dependencies as in `setup.py`
        additional_dependencies:
          [
            "types-PyYAML",
            "types-requests",
            "types-simplejson",
            "types-toml",
            "types-tqdm",
            "types-urllib3",
          ]
