name: Auto Request Review

on:
  pull_request:
    types: [opened, ready_for_review, reopened]
  
jobs:
  auto-request-review:
    name: Auto Request Review
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Request review based on files changed and/or groups author belongs to
        uses: necojackarc/auto-request-review@v0.7.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config: .github/reviewers.yml
