name: Python quality

on:
  push:
    branches:
      - main
    paths-ignore:
      - "interfaces/**"
      - "widgets/**"
      - "api-inference-community/**"
  pull_request:
    types: [assigned, opened, synchronize, reopened]
    paths-ignore:
      - "interfaces/**"
      - "widgets/**"
      - "api-inference-community/**"

jobs:
  check_code_quality:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install .[dev]
    - run: black --check tests src
    - run: isort --check-only tests src
    - run: flake8 tests src
