name: allennlp-docker

on:
  push:
    paths:
      - "api-inference-community/docker_images/allennlp/**"
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Install dependencies
        workdir: api-inference-community
        run: |
          pip install --upgrade pip
          pip install pytest pillow httpx
          pip install -e .
      - run: RUN_DOCKER=1 pytest -sv tests/test_dockers.py::DockerImageTests::test_allennlp
        workdir: api-inference-community
